server:
  port: 8083

spring:
  application:
    name: ms-streaming
  datasource:
    url: jdbc:h2:mem:streamingdb 
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/